# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hA-_t0gHvEcbWxEnBmxzfETJj9ptsUuU
"""

import pandas as pd

def clean_data(rooms=None):
    df = pd.read_csv('cards.csv', delimiter=';', index_col=0)
    df['price_for_m2'] = df['price']/df['area']
    del df['link']
    df.dropna(subset=['price'])
    df = df.loc[df['price'] > 60000]
    if rooms:
        df = df.loc[df['bed'] == rooms]
    df.to_csv('clean_data.csv', sep=',')



if __name__ == '__main__':
    clean_data()